"""
Tests for app.services.audio_service.extract_audio.

Uses FFmpeg's own `lavfi` synthetic source (a generated sine tone) to
create a tiny real test video, rather than mocking FFmpeg itself --
FFmpeg is a fast, already-installed system binary, so there's no
reason not to exercise the real subprocess call and confirm the
output file is actually valid audio.
"""

import subprocess
import wave

import pytest
from fastapi import HTTPException

from app.core.config import settings
from app.services.audio_service import extract_audio


@pytest.fixture
def tiny_test_video(tmp_path):
    """A 1-second mp4 with a synthetic tone, generated by ffmpeg itself."""
    video_path = tmp_path / "tiny.mp4"
    subprocess.run(
        [
            settings.ffmpeg_binary,
            "-y",
            "-f", "lavfi", "-i", "sine=frequency=440:duration=1",
            "-f", "lavfi", "-i", "color=c=blue:size=64x64:duration=1",
            "-shortest",
            str(video_path),
        ],
        capture_output=True,
        check=True,
    )
    return video_path


@pytest.fixture(autouse=True)
def _cleanup_audio_files():
    before = set(settings.audio_dir.glob("*"))
    yield
    after = set(settings.audio_dir.glob("*"))
    for path in after - before:
        path.unlink(missing_ok=True)


def test_extract_audio_produces_mono_16khz_wav(tiny_test_video):
    output_path = extract_audio(tiny_test_video, video_id="test_extract_1")

    assert output_path.exists()
    assert output_path.parent == settings.audio_dir

    with wave.open(str(output_path), "rb") as wav_file:
        assert wav_file.getframerate() == settings.audio_sample_rate_hz
        assert wav_file.getnchannels() == 1


def test_extract_audio_raises_on_invalid_input(tmp_path):
    bogus_path = tmp_path / "not_a_video.mp4"
    bogus_path.write_bytes(b"this is not a real video file")

    with pytest.raises(HTTPException) as exc_info:
        extract_audio(bogus_path, video_id="test_extract_invalid")
    assert exc_info.value.status_code == 500
